[package]
name = "skillchain-nft"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.5.0"
alloy-primitives = "0.6.0"
alloy-sol-types = "0.6.0"

[patch.crates-io]
base64ct = { version = "=1.6.0" }

[features]
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "z"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
